# .github/workflows/build.yml

name: Build Jekyll Site

# Run this workflow manually from the Actions tab
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Ruby, Bundler, and Jekyll ğŸ’
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Build Jekyll site ğŸ”¨
        run: bundle exec jekyll build

      - name: Package the site files ğŸ“¦
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site-html
          path: _site
